### PR TITLE
feat: Add extra headers on APIModel

### PR DESCRIPTION
**Pull request by hugoprudente**
Add capability to provide extra headers when connecting to a Grafana that have a Front Proxy that requires extra headers on the requests.

### CODE REVIEW

**Comment by ZPascal** [comment]
Hello @hugoprudente, thank you very much for your contribution. Could you please customize the unit tests and explain the corresponding use case? I am also thinking of adding a new proxy mode to cover a simple auth proxy.

**Comment by hugoprudente** [comment]
Hey, I'm fixing the unit.test now. 

The use case that I have is my company has a extra front proxy with autentication that we need to use to generate a intermediary token, and that token will request a oficial token for grafana. 

So I need to pass some extra "X-Company-Auth" and some other headers to be able to use the SDK.

**Review by ZPascal — APPROVED** [review]
LGTM. I checked the PR manually and ran the integration tests outside of the GH Actions. I think there is a problem with the GH token and I will analyze this further in a separate issue.

**Comment by ZPascal** [comment]
Thank you @hugoprudente for the contribution.

**Pull request merged**
